// Reef Policy Bus — TerraFabric-shaped gRPC service for distributing signed
// Lobster Trap policy bundles to fleet nodes.
//
// Hierarchy (matches Veea TerraFabric):
//
//   fleet (e.g. "prod-fleet")
//     └── region (e.g. "us-east")
//           └── site (e.g. "store-042")
//                 └── node (e.g. "node-7")
//
// Subscribe is a long-lived server-streaming RPC: a node opens it once and
// the bus pushes any bundle whose scope matches the node identity. Scopes
// narrow as fleet → region → site → node — an empty scope_* field is a
// wildcard at that level.
//
// Signature contract: ed25519 over SHA-256(bundle_yaml), matching the
// `pkg/policysync/cosign.go` (A-6) verifier semantics. The publisher's
// key_id MUST appear in the bus's publisher allowlist before the bundle is
// accepted via Publish; nodes additionally verify the detached signature
// locally before applying.
//
// Fail-closed contract: an Ack with status "verify_failed" tells the bus
// the node detected tampering. The bus records this in its audit log so
// operators can investigate. The node keeps its previous policy active.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.30.2
// source: policy_bus.proto

package policybuspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// NodeIdentity uniquely places a node in the TerraFabric hierarchy. The
// optional svid_subject lets the bus cross-check against the A-6 SVID
// verifier in audit logs.
type NodeIdentity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FleetId       string                 `protobuf:"bytes,1,opt,name=fleet_id,json=fleetId,proto3" json:"fleet_id,omitempty"`
	RegionId      string                 `protobuf:"bytes,2,opt,name=region_id,json=regionId,proto3" json:"region_id,omitempty"`
	SiteId        string                 `protobuf:"bytes,3,opt,name=site_id,json=siteId,proto3" json:"site_id,omitempty"`
	NodeId        string                 `protobuf:"bytes,4,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	SvidSubject   string                 `protobuf:"bytes,5,opt,name=svid_subject,json=svidSubject,proto3" json:"svid_subject,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeIdentity) Reset() {
	*x = NodeIdentity{}
	mi := &file_policy_bus_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeIdentity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeIdentity) ProtoMessage() {}

func (x *NodeIdentity) ProtoReflect() protoreflect.Message {
	mi := &file_policy_bus_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeIdentity.ProtoReflect.Descriptor instead.
func (*NodeIdentity) Descriptor() ([]byte, []int) {
	return file_policy_bus_proto_rawDescGZIP(), []int{0}
}

func (x *NodeIdentity) GetFleetId() string {
	if x != nil {
		return x.FleetId
	}
	return ""
}

func (x *NodeIdentity) GetRegionId() string {
	if x != nil {
		return x.RegionId
	}
	return ""
}

func (x *NodeIdentity) GetSiteId() string {
	if x != nil {
		return x.SiteId
	}
	return ""
}

func (x *NodeIdentity) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodeIdentity) GetSvidSubject() string {
	if x != nil {
		return x.SvidSubject
	}
	return ""
}

type SubscribeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Node  *NodeIdentity          `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	// current_policy_version is the version the node already applied. The
	// server only sends bundles with version > current. Empty string means
	// "send any active bundle".
	CurrentPolicyVersion string `protobuf:"bytes,2,opt,name=current_policy_version,json=currentPolicyVersion,proto3" json:"current_policy_version,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_policy_bus_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_policy_bus_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_policy_bus_proto_rawDescGZIP(), []int{1}
}

func (x *SubscribeRequest) GetNode() *NodeIdentity {
	if x != nil {
		return x.Node
	}
	return nil
}

func (x *SubscribeRequest) GetCurrentPolicyVersion() string {
	if x != nil {
		return x.CurrentPolicyVersion
	}
	return ""
}

// SignedBundle is the unit of policy distribution. bundle_yaml is the
// canonical YAML the Lobster Trap policy loader consumes. signature is
// ed25519 over SHA-256(bundle_yaml), accepting either raw 64 bytes or
// base64 (the cosign verifier handles both shapes — see
// pkg/policysync/cosign.go decodeSignature).
type SignedBundle struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	BundleId string                 `protobuf:"bytes,1,opt,name=bundle_id,json=bundleId,proto3" json:"bundle_id,omitempty"`
	Version  string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// Scope is the TerraFabric hierarchy filter. Empty fields are wildcards.
	// E.g. scope_fleet_id="prod-fleet" + empty region/site = "all prod-fleet
	// nodes regardless of region/site".
	ScopeFleetId    string `protobuf:"bytes,3,opt,name=scope_fleet_id,json=scopeFleetId,proto3" json:"scope_fleet_id,omitempty"`
	ScopeRegionId   string `protobuf:"bytes,4,opt,name=scope_region_id,json=scopeRegionId,proto3" json:"scope_region_id,omitempty"`
	ScopeSiteId     string `protobuf:"bytes,5,opt,name=scope_site_id,json=scopeSiteId,proto3" json:"scope_site_id,omitempty"`
	ScopeNodeId     string `protobuf:"bytes,6,opt,name=scope_node_id,json=scopeNodeId,proto3" json:"scope_node_id,omitempty"`
	BundleYaml      []byte `protobuf:"bytes,7,opt,name=bundle_yaml,json=bundleYaml,proto3" json:"bundle_yaml,omitempty"`
	Signature       []byte `protobuf:"bytes,8,opt,name=signature,proto3" json:"signature,omitempty"`
	SignerKeyId     string `protobuf:"bytes,9,opt,name=signer_key_id,json=signerKeyId,proto3" json:"signer_key_id,omitempty"`
	PublishedAtUnix int64  `protobuf:"varint,10,opt,name=published_at_unix,json=publishedAtUnix,proto3" json:"published_at_unix,omitempty"`
	// expires_at_unix is optional; 0 means never expires.
	ExpiresAtUnix int64 `protobuf:"varint,11,opt,name=expires_at_unix,json=expiresAtUnix,proto3" json:"expires_at_unix,omitempty"`
	// is_heartbeat distinguishes server keep-alive frames from actual policy
	// pushes. Heartbeats carry no bundle_yaml or signature.
	IsHeartbeat   bool `protobuf:"varint,12,opt,name=is_heartbeat,json=isHeartbeat,proto3" json:"is_heartbeat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignedBundle) Reset() {
	*x = SignedBundle{}
	mi := &file_policy_bus_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignedBundle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignedBundle) ProtoMessage() {}

func (x *SignedBundle) ProtoReflect() protoreflect.Message {
	mi := &file_policy_bus_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignedBundle.ProtoReflect.Descriptor instead.
func (*SignedBundle) Descriptor() ([]byte, []int) {
	return file_policy_bus_proto_rawDescGZIP(), []int{2}
}

func (x *SignedBundle) GetBundleId() string {
	if x != nil {
		return x.BundleId
	}
	return ""
}

func (x *SignedBundle) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *SignedBundle) GetScopeFleetId() string {
	if x != nil {
		return x.ScopeFleetId
	}
	return ""
}

func (x *SignedBundle) GetScopeRegionId() string {
	if x != nil {
		return x.ScopeRegionId
	}
	return ""
}

func (x *SignedBundle) GetScopeSiteId() string {
	if x != nil {
		return x.ScopeSiteId
	}
	return ""
}

func (x *SignedBundle) GetScopeNodeId() string {
	if x != nil {
		return x.ScopeNodeId
	}
	return ""
}

func (x *SignedBundle) GetBundleYaml() []byte {
	if x != nil {
		return x.BundleYaml
	}
	return nil
}

func (x *SignedBundle) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *SignedBundle) GetSignerKeyId() string {
	if x != nil {
		return x.SignerKeyId
	}
	return ""
}

func (x *SignedBundle) GetPublishedAtUnix() int64 {
	if x != nil {
		return x.PublishedAtUnix
	}
	return 0
}

func (x *SignedBundle) GetExpiresAtUnix() int64 {
	if x != nil {
		return x.ExpiresAtUnix
	}
	return 0
}

func (x *SignedBundle) GetIsHeartbeat() bool {
	if x != nil {
		return x.IsHeartbeat
	}
	return false
}

type AckRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Node           *NodeIdentity          `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	BundleId       string                 `protobuf:"bytes,2,opt,name=bundle_id,json=bundleId,proto3" json:"bundle_id,omitempty"`
	AppliedVersion string                 `protobuf:"bytes,3,opt,name=applied_version,json=appliedVersion,proto3" json:"applied_version,omitempty"`
	// ack_status ∈ {"applied", "verify_failed", "policy_parse_failed",
	// "kept_old_active", "scope_mismatch"}.
	AckStatus     string `protobuf:"bytes,4,opt,name=ack_status,json=ackStatus,proto3" json:"ack_status,omitempty"`
	Detail        string `protobuf:"bytes,5,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckRequest) Reset() {
	*x = AckRequest{}
	mi := &file_policy_bus_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckRequest) ProtoMessage() {}

func (x *AckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_policy_bus_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckRequest.ProtoReflect.Descriptor instead.
func (*AckRequest) Descriptor() ([]byte, []int) {
	return file_policy_bus_proto_rawDescGZIP(), []int{3}
}

func (x *AckRequest) GetNode() *NodeIdentity {
	if x != nil {
		return x.Node
	}
	return nil
}

func (x *AckRequest) GetBundleId() string {
	if x != nil {
		return x.BundleId
	}
	return ""
}

func (x *AckRequest) GetAppliedVersion() string {
	if x != nil {
		return x.AppliedVersion
	}
	return ""
}

func (x *AckRequest) GetAckStatus() string {
	if x != nil {
		return x.AckStatus
	}
	return ""
}

func (x *AckRequest) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

type AckResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// audit_id correlates with the bus's audit log entry — operators grep
	// for this when investigating propagation.
	AuditId       string `protobuf:"bytes,1,opt,name=audit_id,json=auditId,proto3" json:"audit_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckResponse) Reset() {
	*x = AckResponse{}
	mi := &file_policy_bus_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckResponse) ProtoMessage() {}

func (x *AckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_policy_bus_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckResponse.ProtoReflect.Descriptor instead.
func (*AckResponse) Descriptor() ([]byte, []int) {
	return file_policy_bus_proto_rawDescGZIP(), []int{4}
}

func (x *AckResponse) GetAuditId() string {
	if x != nil {
		return x.AuditId
	}
	return ""
}

type PublishRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Bundle *SignedBundle          `protobuf:"bytes,1,opt,name=bundle,proto3" json:"bundle,omitempty"`
	// admin_token is the pre-shared secret loaded from
	// REEF_POLICY_BUS_ADMIN_TOKEN. Mismatch → reject + audit.
	AdminToken    string `protobuf:"bytes,2,opt,name=admin_token,json=adminToken,proto3" json:"admin_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishRequest) Reset() {
	*x = PublishRequest{}
	mi := &file_policy_bus_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishRequest) ProtoMessage() {}

func (x *PublishRequest) ProtoReflect() protoreflect.Message {
	mi := &file_policy_bus_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishRequest.ProtoReflect.Descriptor instead.
func (*PublishRequest) Descriptor() ([]byte, []int) {
	return file_policy_bus_proto_rawDescGZIP(), []int{5}
}

func (x *PublishRequest) GetBundle() *SignedBundle {
	if x != nil {
		return x.Bundle
	}
	return nil
}

func (x *PublishRequest) GetAdminToken() string {
	if x != nil {
		return x.AdminToken
	}
	return ""
}

type PublishResponse struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	BundleId string                 `protobuf:"bytes,1,opt,name=bundle_id,json=bundleId,proto3" json:"bundle_id,omitempty"`
	// fleet_recipient_count is the number of nodes currently subscribed
	// whose scope matches this bundle.
	FleetRecipientCount int64 `protobuf:"varint,2,opt,name=fleet_recipient_count,json=fleetRecipientCount,proto3" json:"fleet_recipient_count,omitempty"`
	// audit_id correlates with the publish audit entry.
	AuditId       string `protobuf:"bytes,3,opt,name=audit_id,json=auditId,proto3" json:"audit_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishResponse) Reset() {
	*x = PublishResponse{}
	mi := &file_policy_bus_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishResponse) ProtoMessage() {}

func (x *PublishResponse) ProtoReflect() protoreflect.Message {
	mi := &file_policy_bus_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishResponse.ProtoReflect.Descriptor instead.
func (*PublishResponse) Descriptor() ([]byte, []int) {
	return file_policy_bus_proto_rawDescGZIP(), []int{6}
}

func (x *PublishResponse) GetBundleId() string {
	if x != nil {
		return x.BundleId
	}
	return ""
}

func (x *PublishResponse) GetFleetRecipientCount() int64 {
	if x != nil {
		return x.FleetRecipientCount
	}
	return 0
}

func (x *PublishResponse) GetAuditId() string {
	if x != nil {
		return x.AuditId
	}
	return ""
}

type HealthzRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthzRequest) Reset() {
	*x = HealthzRequest{}
	mi := &file_policy_bus_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthzRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthzRequest) ProtoMessage() {}

func (x *HealthzRequest) ProtoReflect() protoreflect.Message {
	mi := &file_policy_bus_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthzRequest.ProtoReflect.Descriptor instead.
func (*HealthzRequest) Descriptor() ([]byte, []int) {
	return file_policy_bus_proto_rawDescGZIP(), []int{7}
}

type HealthzResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// status ∈ {"ok", "degraded"}. Both 200; degraded signals a non-fatal
	// subsystem failure (e.g. allowlist file unreadable but cache still hot).
	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	// active_subscribers is the count of long-lived Subscribe streams.
	ActiveSubscribers int64 `protobuf:"varint,2,opt,name=active_subscribers,json=activeSubscribers,proto3" json:"active_subscribers,omitempty"`
	// active_bundles is the count of currently-cached bundles.
	ActiveBundles int64 `protobuf:"varint,3,opt,name=active_bundles,json=activeBundles,proto3" json:"active_bundles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthzResponse) Reset() {
	*x = HealthzResponse{}
	mi := &file_policy_bus_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthzResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthzResponse) ProtoMessage() {}

func (x *HealthzResponse) ProtoReflect() protoreflect.Message {
	mi := &file_policy_bus_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthzResponse.ProtoReflect.Descriptor instead.
func (*HealthzResponse) Descriptor() ([]byte, []int) {
	return file_policy_bus_proto_rawDescGZIP(), []int{8}
}

func (x *HealthzResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthzResponse) GetActiveSubscribers() int64 {
	if x != nil {
		return x.ActiveSubscribers
	}
	return 0
}

func (x *HealthzResponse) GetActiveBundles() int64 {
	if x != nil {
		return x.ActiveBundles
	}
	return 0
}

var File_policy_bus_proto protoreflect.FileDescriptor

const file_policy_bus_proto_rawDesc = "" +
	"\n" +
	"\x10policy_bus.proto\x12\x12reef.policy_bus.v1\"\x9b\x01\n" +
	"\fNodeIdentity\x12\x19\n" +
	"\bfleet_id\x18\x01 \x01(\tR\afleetId\x12\x1b\n" +
	"\tregion_id\x18\x02 \x01(\tR\bregionId\x12\x17\n" +
	"\asite_id\x18\x03 \x01(\tR\x06siteId\x12\x17\n" +
	"\anode_id\x18\x04 \x01(\tR\x06nodeId\x12!\n" +
	"\fsvid_subject\x18\x05 \x01(\tR\vsvidSubject\"~\n" +
	"\x10SubscribeRequest\x124\n" +
	"\x04node\x18\x01 \x01(\v2 .reef.policy_bus.v1.NodeIdentityR\x04node\x124\n" +
	"\x16current_policy_version\x18\x02 \x01(\tR\x14currentPolicyVersion\"\xb5\x03\n" +
	"\fSignedBundle\x12\x1b\n" +
	"\tbundle_id\x18\x01 \x01(\tR\bbundleId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12$\n" +
	"\x0escope_fleet_id\x18\x03 \x01(\tR\fscopeFleetId\x12&\n" +
	"\x0fscope_region_id\x18\x04 \x01(\tR\rscopeRegionId\x12\"\n" +
	"\rscope_site_id\x18\x05 \x01(\tR\vscopeSiteId\x12\"\n" +
	"\rscope_node_id\x18\x06 \x01(\tR\vscopeNodeId\x12\x1f\n" +
	"\vbundle_yaml\x18\a \x01(\fR\n" +
	"bundleYaml\x12\x1c\n" +
	"\tsignature\x18\b \x01(\fR\tsignature\x12\"\n" +
	"\rsigner_key_id\x18\t \x01(\tR\vsignerKeyId\x12*\n" +
	"\x11published_at_unix\x18\n" +
	" \x01(\x03R\x0fpublishedAtUnix\x12&\n" +
	"\x0fexpires_at_unix\x18\v \x01(\x03R\rexpiresAtUnix\x12!\n" +
	"\fis_heartbeat\x18\f \x01(\bR\visHeartbeat\"\xbf\x01\n" +
	"\n" +
	"AckRequest\x124\n" +
	"\x04node\x18\x01 \x01(\v2 .reef.policy_bus.v1.NodeIdentityR\x04node\x12\x1b\n" +
	"\tbundle_id\x18\x02 \x01(\tR\bbundleId\x12'\n" +
	"\x0fapplied_version\x18\x03 \x01(\tR\x0eappliedVersion\x12\x1d\n" +
	"\n" +
	"ack_status\x18\x04 \x01(\tR\tackStatus\x12\x16\n" +
	"\x06detail\x18\x05 \x01(\tR\x06detail\"(\n" +
	"\vAckResponse\x12\x19\n" +
	"\baudit_id\x18\x01 \x01(\tR\aauditId\"k\n" +
	"\x0ePublishRequest\x128\n" +
	"\x06bundle\x18\x01 \x01(\v2 .reef.policy_bus.v1.SignedBundleR\x06bundle\x12\x1f\n" +
	"\vadmin_token\x18\x02 \x01(\tR\n" +
	"adminToken\"}\n" +
	"\x0fPublishResponse\x12\x1b\n" +
	"\tbundle_id\x18\x01 \x01(\tR\bbundleId\x122\n" +
	"\x15fleet_recipient_count\x18\x02 \x01(\x03R\x13fleetRecipientCount\x12\x19\n" +
	"\baudit_id\x18\x03 \x01(\tR\aauditId\"\x10\n" +
	"\x0eHealthzRequest\"\x7f\n" +
	"\x0fHealthzResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12-\n" +
	"\x12active_subscribers\x18\x02 \x01(\x03R\x11activeSubscribers\x12%\n" +
	"\x0eactive_bundles\x18\x03 \x01(\x03R\ractiveBundles2\xd2\x02\n" +
	"\tPolicyBus\x12U\n" +
	"\tSubscribe\x12$.reef.policy_bus.v1.SubscribeRequest\x1a .reef.policy_bus.v1.SignedBundle0\x01\x12F\n" +
	"\x03Ack\x12\x1e.reef.policy_bus.v1.AckRequest\x1a\x1f.reef.policy_bus.v1.AckResponse\x12R\n" +
	"\aPublish\x12\".reef.policy_bus.v1.PublishRequest\x1a#.reef.policy_bus.v1.PublishResponse\x12R\n" +
	"\aHealthz\x12\".reef.policy_bus.v1.HealthzRequest\x1a#.reef.policy_bus.v1.HealthzResponseBYZWgithub.com/Yashash4/reef-mcp-registry/lobstertrap-reef/pkg/policysync/proto;policybuspbb\x06proto3"

var (
	file_policy_bus_proto_rawDescOnce sync.Once
	file_policy_bus_proto_rawDescData []byte
)

func file_policy_bus_proto_rawDescGZIP() []byte {
	file_policy_bus_proto_rawDescOnce.Do(func() {
		file_policy_bus_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_policy_bus_proto_rawDesc), len(file_policy_bus_proto_rawDesc)))
	})
	return file_policy_bus_proto_rawDescData
}

var file_policy_bus_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_policy_bus_proto_goTypes = []any{
	(*NodeIdentity)(nil),     // 0: reef.policy_bus.v1.NodeIdentity
	(*SubscribeRequest)(nil), // 1: reef.policy_bus.v1.SubscribeRequest
	(*SignedBundle)(nil),     // 2: reef.policy_bus.v1.SignedBundle
	(*AckRequest)(nil),       // 3: reef.policy_bus.v1.AckRequest
	(*AckResponse)(nil),      // 4: reef.policy_bus.v1.AckResponse
	(*PublishRequest)(nil),   // 5: reef.policy_bus.v1.PublishRequest
	(*PublishResponse)(nil),  // 6: reef.policy_bus.v1.PublishResponse
	(*HealthzRequest)(nil),   // 7: reef.policy_bus.v1.HealthzRequest
	(*HealthzResponse)(nil),  // 8: reef.policy_bus.v1.HealthzResponse
}
var file_policy_bus_proto_depIdxs = []int32{
	0, // 0: reef.policy_bus.v1.SubscribeRequest.node:type_name -> reef.policy_bus.v1.NodeIdentity
	0, // 1: reef.policy_bus.v1.AckRequest.node:type_name -> reef.policy_bus.v1.NodeIdentity
	2, // 2: reef.policy_bus.v1.PublishRequest.bundle:type_name -> reef.policy_bus.v1.SignedBundle
	1, // 3: reef.policy_bus.v1.PolicyBus.Subscribe:input_type -> reef.policy_bus.v1.SubscribeRequest
	3, // 4: reef.policy_bus.v1.PolicyBus.Ack:input_type -> reef.policy_bus.v1.AckRequest
	5, // 5: reef.policy_bus.v1.PolicyBus.Publish:input_type -> reef.policy_bus.v1.PublishRequest
	7, // 6: reef.policy_bus.v1.PolicyBus.Healthz:input_type -> reef.policy_bus.v1.HealthzRequest
	2, // 7: reef.policy_bus.v1.PolicyBus.Subscribe:output_type -> reef.policy_bus.v1.SignedBundle
	4, // 8: reef.policy_bus.v1.PolicyBus.Ack:output_type -> reef.policy_bus.v1.AckResponse
	6, // 9: reef.policy_bus.v1.PolicyBus.Publish:output_type -> reef.policy_bus.v1.PublishResponse
	8, // 10: reef.policy_bus.v1.PolicyBus.Healthz:output_type -> reef.policy_bus.v1.HealthzResponse
	7, // [7:11] is the sub-list for method output_type
	3, // [3:7] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_policy_bus_proto_init() }
func file_policy_bus_proto_init() {
	if File_policy_bus_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_policy_bus_proto_rawDesc), len(file_policy_bus_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_policy_bus_proto_goTypes,
		DependencyIndexes: file_policy_bus_proto_depIdxs,
		MessageInfos:      file_policy_bus_proto_msgTypes,
	}.Build()
	File_policy_bus_proto = out.File
	file_policy_bus_proto_goTypes = nil
	file_policy_bus_proto_depIdxs = nil
}
