// Reef Policy Bus — TerraFabric-shaped gRPC service for distributing signed
// Lobster Trap policy bundles to fleet nodes.
//
// Hierarchy (matches Veea TerraFabric):
//
//   fleet (e.g. "prod-fleet")
//     └── region (e.g. "us-east")
//           └── site (e.g. "store-042")
//                 └── node (e.g. "node-7")
//
// Subscribe is a long-lived server-streaming RPC: a node opens it once and
// the bus pushes any bundle whose scope matches the node identity. Scopes
// narrow as fleet → region → site → node — an empty scope_* field is a
// wildcard at that level.
//
// Signature contract: ed25519 over SHA-256(bundle_yaml), matching the
// `pkg/policysync/cosign.go` (A-6) verifier semantics. The publisher's
// key_id MUST appear in the bus's publisher allowlist before the bundle is
// accepted via Publish; nodes additionally verify the detached signature
// locally before applying.
//
// Fail-closed contract: an Ack with status "verify_failed" tells the bus
// the node detected tampering. The bus records this in its audit log so
// operators can investigate. The node keeps its previous policy active.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v6.30.2
// source: policy_bus.proto

package policybuspb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PolicyBus_Subscribe_FullMethodName = "/reef.policy_bus.v1.PolicyBus/Subscribe"
	PolicyBus_Ack_FullMethodName       = "/reef.policy_bus.v1.PolicyBus/Ack"
	PolicyBus_Publish_FullMethodName   = "/reef.policy_bus.v1.PolicyBus/Publish"
	PolicyBus_Healthz_FullMethodName   = "/reef.policy_bus.v1.PolicyBus/Healthz"
)

// PolicyBusClient is the client API for PolicyBus service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PolicyBus is the gRPC service the control plane exposes to fleet nodes.
type PolicyBusClient interface {
	// Subscribe is the long-lived server-streaming entrypoint. A node opens
	// it once at startup; the bus pushes any matching bundle (newer than the
	// node's current_policy_version) plus periodic heartbeats. On stream
	// drop, the node reconnects with exponential backoff.
	Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SignedBundle], error)
	// Ack is unary. After the node applies (or rejects) a bundle, it acks
	// with the outcome so the bus can record propagation status + drift.
	Ack(ctx context.Context, in *AckRequest, opts ...grpc.CallOption) (*AckResponse, error)
	// Publish is unary. Admins push a new signed bundle. The bus verifies
	// the publisher allowlist + signature before broadcasting to subscribers.
	// Authentication is via the admin_token field (pre-shared secret in v1;
	// Phase 2 hardens with mTLS + signed JWT).
	Publish(ctx context.Context, in *PublishRequest, opts ...grpc.CallOption) (*PublishResponse, error)
	// Healthz is unary. Lightweight check for docker-compose healthcheck +
	// dashboard liveness probes.
	Healthz(ctx context.Context, in *HealthzRequest, opts ...grpc.CallOption) (*HealthzResponse, error)
}

type policyBusClient struct {
	cc grpc.ClientConnInterface
}

func NewPolicyBusClient(cc grpc.ClientConnInterface) PolicyBusClient {
	return &policyBusClient{cc}
}

func (c *policyBusClient) Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SignedBundle], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PolicyBus_ServiceDesc.Streams[0], PolicyBus_Subscribe_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeRequest, SignedBundle]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PolicyBus_SubscribeClient = grpc.ServerStreamingClient[SignedBundle]

func (c *policyBusClient) Ack(ctx context.Context, in *AckRequest, opts ...grpc.CallOption) (*AckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AckResponse)
	err := c.cc.Invoke(ctx, PolicyBus_Ack_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *policyBusClient) Publish(ctx context.Context, in *PublishRequest, opts ...grpc.CallOption) (*PublishResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublishResponse)
	err := c.cc.Invoke(ctx, PolicyBus_Publish_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *policyBusClient) Healthz(ctx context.Context, in *HealthzRequest, opts ...grpc.CallOption) (*HealthzResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthzResponse)
	err := c.cc.Invoke(ctx, PolicyBus_Healthz_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PolicyBusServer is the server API for PolicyBus service.
// All implementations must embed UnimplementedPolicyBusServer
// for forward compatibility.
//
// PolicyBus is the gRPC service the control plane exposes to fleet nodes.
type PolicyBusServer interface {
	// Subscribe is the long-lived server-streaming entrypoint. A node opens
	// it once at startup; the bus pushes any matching bundle (newer than the
	// node's current_policy_version) plus periodic heartbeats. On stream
	// drop, the node reconnects with exponential backoff.
	Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[SignedBundle]) error
	// Ack is unary. After the node applies (or rejects) a bundle, it acks
	// with the outcome so the bus can record propagation status + drift.
	Ack(context.Context, *AckRequest) (*AckResponse, error)
	// Publish is unary. Admins push a new signed bundle. The bus verifies
	// the publisher allowlist + signature before broadcasting to subscribers.
	// Authentication is via the admin_token field (pre-shared secret in v1;
	// Phase 2 hardens with mTLS + signed JWT).
	Publish(context.Context, *PublishRequest) (*PublishResponse, error)
	// Healthz is unary. Lightweight check for docker-compose healthcheck +
	// dashboard liveness probes.
	Healthz(context.Context, *HealthzRequest) (*HealthzResponse, error)
	mustEmbedUnimplementedPolicyBusServer()
}

// UnimplementedPolicyBusServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPolicyBusServer struct{}

func (UnimplementedPolicyBusServer) Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[SignedBundle]) error {
	return status.Error(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedPolicyBusServer) Ack(context.Context, *AckRequest) (*AckResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ack not implemented")
}
func (UnimplementedPolicyBusServer) Publish(context.Context, *PublishRequest) (*PublishResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Publish not implemented")
}
func (UnimplementedPolicyBusServer) Healthz(context.Context, *HealthzRequest) (*HealthzResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Healthz not implemented")
}
func (UnimplementedPolicyBusServer) mustEmbedUnimplementedPolicyBusServer() {}
func (UnimplementedPolicyBusServer) testEmbeddedByValue()                   {}

// UnsafePolicyBusServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PolicyBusServer will
// result in compilation errors.
type UnsafePolicyBusServer interface {
	mustEmbedUnimplementedPolicyBusServer()
}

func RegisterPolicyBusServer(s grpc.ServiceRegistrar, srv PolicyBusServer) {
	// If the following call panics, it indicates UnimplementedPolicyBusServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PolicyBus_ServiceDesc, srv)
}

func _PolicyBus_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(PolicyBusServer).Subscribe(m, &grpc.GenericServerStream[SubscribeRequest, SignedBundle]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PolicyBus_SubscribeServer = grpc.ServerStreamingServer[SignedBundle]

func _PolicyBus_Ack_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PolicyBusServer).Ack(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PolicyBus_Ack_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PolicyBusServer).Ack(ctx, req.(*AckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PolicyBus_Publish_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PolicyBusServer).Publish(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PolicyBus_Publish_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PolicyBusServer).Publish(ctx, req.(*PublishRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PolicyBus_Healthz_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthzRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PolicyBusServer).Healthz(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PolicyBus_Healthz_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PolicyBusServer).Healthz(ctx, req.(*HealthzRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PolicyBus_ServiceDesc is the grpc.ServiceDesc for PolicyBus service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PolicyBus_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "reef.policy_bus.v1.PolicyBus",
	HandlerType: (*PolicyBusServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ack",
			Handler:    _PolicyBus_Ack_Handler,
		},
		{
			MethodName: "Publish",
			Handler:    _PolicyBus_Publish_Handler,
		},
		{
			MethodName: "Healthz",
			Handler:    _PolicyBus_Healthz_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _PolicyBus_Subscribe_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "policy_bus.proto",
}
